import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export async function getServerSideProps(context) {
  const api = process.env.NEXT_PUBLIC_API;
  const res = await fetch(`https://api.nasa.gov/planetary/apod?api_key=${api}`);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data }, // will be passed to the page component as props
  };
}
export default function Home({ data }) {
  const [like, setLike] = useState();
  const key = data.date.toString();
  useEffect(() => {
    const likeStatus = localStorage.getItem(key);

    if (likeStatus === "false") {
      setLike(false);
    } else {
      setLike(true);
    }
  }, []);
  function onClick(e) {
    // localStorage.setItem(data.date.toString(), !like);

    if (like === true) {
      localStorage.setItem(key, false);
      setLike(false);
    } else {
      localStorage.setItem(key, true);
      setLike(true);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{data.title} </h1>
      <img style={{ maxWidth: "100%" }} src={data.hdurl} />
      {like === true ? (
        <button onClick={onClick}>unlike</button>
      ) : (
        <button onClick={onClick}>like</button>
      )}
    </div>
  );
}
